### ISSUE TITLE
Question about z2m configuration..

### ISSUE THREAD

**Issue by itProfi** [jorticus/pio-platform-nxp-jennic#1]
Hello friend! Thank for you work! Can you say, what the string you write in z2m configuration in serial - adapter section?

**Comment by jorticus** [comment]
Do you mean Zigbee2Mqtt? If so, I have not tried building a router, and I don't think there's support for the JNxx series of chips anyway (I've only seen support for TI CCxx chips & EFM32).

My main goal with this project is really to build end devices (such as lamps, switches). You can join your JNxx end device to any existing ZigBee network. 

For my network, I used a CC2531 USB stick, and configured Zigbee2Mqtt with the default settings. I then paired my JNxx chip to the network and it automatically showed up as a light bulb. 

Hope that answers your question?

**Comment by itProfi** [comment]
Yes, i understand! In our Telegram group https://t.me/xiaomi_gw_hack we allready build firmware, based on Zigate (it use name	JN-AN-1216-Zigbee-3-0-IoT-ControlBridge) with coordinator and router role.
But some end devices, like xiaomi door sensor, temperature etc has Zigbee HA 1.2 firmware and not correct work with our firmware with routers..
https://github.com/openlumi/JN-ZigbeeNodeControlBridge-firmware
